# Generated by Django 3.2.4 on 2021-06-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('nombre_especie', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('chip', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('imagen', models.ImageField(upload_to='fotos')),
                ('edad', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=60)),
                ('esterilizado', models.CharField(max_length=60)),
                ('nombre_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ong_ayuda.especie')),
            ],
        ),
    ]
